# docker-compose up -d
# docker-compose exec dev bash
# mix phx.new new_project
# in new_project/config/dev.exs replace hostname: "localhost" to hostname: "db",
# cd new_project && mix ecto.create && mix phx.server
version: '3'
services:
  dev:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - .:/code
    ports:
        - 4000:4000
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
    phoenix_code:
